@baseAddress=https://localhost:7565
#@baseAddress=https://<tunnel>-7565.<cluster>.devtunnels.ms

### Get OpenApi Spec
GET {{baseAddress}}/openapi/v1.json
X-Tunnel-Authorization: tunnel <token>

### Weather Forecast
GET {{baseAddress}}/weatherforecast
