# @baseAddress=https://localhost:7565
@baseAddress=https://sample-devtunnel-api-7565.usw2.devtunnels.ms

### Get OpenApi Spec
GET {{baseAddress}}/openapi/v1.json

### Weather Forecast
GET {{baseAddress}}/weatherforecast
