<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.DevTunnels.Connections" />
  </ItemGroup>

</Project>
